# Generated by Django 4.0.3 on 2022-03-25 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Poster_Link', models.TextField()),
                ('original_title', models.TextField()),
                ('Released_Year', models.IntegerField()),
                ('Certificate', models.TextField()),
                ('Runtime', models.IntegerField()),
                ('Genre', models.TextField()),
                ('IMDB_Rating', models.FloatField()),
                ('Overview', models.TextField(default='Overview')),
                ('Meta_score', models.IntegerField()),
                ('Director', models.TextField()),
                ('Star1', models.TextField()),
                ('Star2', models.TextField()),
                ('Star3', models.TextField()),
                ('Star4', models.TextField()),
                ('Gross', models.IntegerField()),
                ('keywords', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch', models.BooleanField(default=False)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommend.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
